---
title: "austin_cpa_corpo_filings"
output: html_document
date: "2025-01-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
financial_markers_base<- c('LTD',
                       'L T D',
                       'L\\.?T\\.?D\\.?',
                       'LLC',
                       'L L C',
                       'L\\.?L\\.?C\\.?',
                       'LP',
                       'L P',
                       'L\\.?P\\.?',
                       'LLLP',
                       'L L L P',
                       'L\\.?L\\.?L\\.?P\\.?',
                       'INC',
                       'I N C',
                       'I\\.?N\\.?C\\.?',
                       'LC',
                       'L C',
                       'L\\.?C\\.?')
financial_markers_supp <- c('MORTG',
                       'RENT',
                       'MARKET',
                       'INVEST',
                       'PROP',
                       'MANAGE',
                       'MGT',
                       'MGMT',
                       'ASSET',
                       'JOINT',
                       'VENTURE',
                       'VNT',
                       'LIMIT',
                       'PARTN',
                       'PRTN',
                       'BANK',
                       'ASSOC',
                       'EQUIT',
                       'REALT',
                       'OWNER',
                       'HOLDING',
                       'DEVELOP',
                       'COMP',
                       'CORP',
                       'AQUISI',
                       'CONDO',
                       'C/O',
                       '[[:digit:]]',
                       'BORROWER')

financial_marker_string <- paste(paste(financial_markers_base, 
                                       collapse = '|'),
                                 paste(financial_markers_supp, 
                                       collapse = '|'),
                                 sep = '|')
financial_marker_base_string <- paste(financial_markers_base, 
                                       collapse = '|')
```
## R Markdown



```{r}
library(readr)
library(rvest)
library(selenider)
library(dplyr)
library(selenium)
# library(chromote)

library(readr)
# user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36'

#Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
target_properties <- read_csv('target_properties.csv')
target_properties[,grepl('^X',
                         colnames(target_properties)
                         )] <- NULL

library(future)
library(foreach)


get_business_details = function(business_string){

  business_name <- regmatches(business_string,
                              regexpr("(?<=^).*(?=\\n)",
                                      business_string,
                                      perl = TRUE))
  ttn_matches <- regmatches(business_string,
                            regexpr("(?<=Texas Taxpayer Number:\\n).*(?=\\n)",
                                    business_string, 
                                    perl = TRUE))
  
  mail_add_matches <- regmatches(business_string,
                            regexpr("(?<=Mailing Address:\\n).*(?=\\n)",
                                    business_string, 
                                    perl = TRUE))

  right_to_transact_status <- regmatches(business_string,
              regexpr("(?<=Right to Transact Business in Texas:\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  state_of_formation <- regmatches(business_string,
                            regexpr("(?<=State of Formation:\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  sos_registration_status <- regmatches(business_string,
                            regexpr("(?<=updated each business day\\):\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  
  effective_sos_reg_date <- regmatches(business_string,
                            regexpr("(?<=SOS Registration Date:\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  
  tx_sos_file_num <- regmatches(business_string,
                            regexpr("(?<=SOS File Number:\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  
  registered_agent_name <- regmatches(business_string,
                            regexpr("(?<=Registered Agent Name:\\n).*(?=\\n)",
                                    business_string, perl = TRUE))
  
  business_details_table = data.frame(corp_business_name = business_name,
              corp_TTN = ttn_matches,
             corp_mail_address = mail_add_matches,
             corp_right_to_transact_business_tx_status = right_to_transact_status,
             corp_state_of_formation = state_of_formation ,
             corp_sos_registration_status = sos_registration_status,
             corp_effective_sos_registration_date = effective_sos_reg_date,
             corp_tx_sos_file_num = tx_sos_file_num,
             corp_registered_agent_name = registered_agent_name)
  
  return(business_details_table)
}


type_name = function(entity_name_search_box,
                     name,
                     try = 1
                     ){
  if(try==1){
    print('1')
    elem_set_value(entity_name_search_box,
                 trimws(gsub(paste(',?[[:space:]]{1}(?=',
                                    financial_marker_base_string,
                                    ')', sep = ''),
                             ', ',
                             name,
                             perl = TRUE)
                        )
                 )
  }
  if(try==2){
    print('2')
    elem_set_value(entity_name_search_box,
                 trimws(gsub(paste(',?[[:space:]]{1}(?=',
                                    financial_marker_base_string,
                                    ')', sep = ''),
                             ' ',
                             name,
                             perl = TRUE)
                        )
                 )
    
  }
  if(try==3){
    print('3')
    elem_set_value(entity_name_search_box,
                 trimws(gsub(paste(',?[[:space:]]{1}',
                                    financial_marker_base_string,
                                   sep = ''),
                             '',
                             name,
                             perl = TRUE)
                        )
                 )
  }
  
}

wait_to_click = function(element){
  element %>%
    elem_expect(is_present && is_visible, 
                timeout = 60) %>%
    elem_click()
  
}


officer_business_bind = function(owner_table,
                                 business_details_table_parse
                                 ){
  foreach(index = 1:nrow(owner_table),
                       .combine = 'rbind') %do% {
                         cbind(owner_table[index,],
                               business_details_table_parse)
      }
}
scrape_owner = function(owner_name,
                        situs_pID,
                        situs_address,
                        veneer_owner,
                       veneer_owner_mail_address,
                       depth = 0,
                       owner_title = NA,
                       owner_mail_address = NA,
                       business_details_table = NA){
  session <- selenider_session(session = "selenium",
                             browser = 'chrome',
                  # options = chromote_options(headless = FALSE),
                  driver = list(selenium_server(version = '4.29.0',
                                                  interactive = FALSE,
                                                  path = getwd(), temp = TRUE),
                                SeleniumSession$new(browser = 'chrome',
                    capabilities = selenium::chrome_options(args=c('--headless',
                  '--no-sandbox',
                  '--disable-extensions',
                  '--disable-browser-side-navigation',
                  '--disable-dev-shm-usage',
                  "--disable-gpu",
                  "--proxy-server='direct://'",
                  '--proxy-bypass-list=*')),
                    timeout = 60))
                  ,
                  timeout = 60
                  )
  # Go to global website
  
  base_url = 'https://comptroller.texas.gov/'
  open_url("https://mycpa.cpa.state.tx.us/coa/")
  entity_name_search_box <- s("#name")
  search_button <- s("#submitBtn")

  type_name(entity_name_search_box,
            owner_name,
            try = 1)
  wait_to_click(search_button)
  search_result <-  s('.odd') %>% elem_text()
  if(search_result=="No data available in table"){
    type_name(entity_name_search_box,
            owner_name,
            try = 2)
   wait_to_click(search_button)
    search_result <-  s('.odd') %>% elem_text()
    
  }
  if(search_result=="No data available in table"){
    type_name(entity_name_search_box,
            owner_name,
            try = 3)
    wait_to_click(search_button)
    search_result <-  s('.odd') %>% elem_text()
    
  }
  if(search_result=="No data available in table"){
    return(NULL)
  }
  link_addend <- s('.odd') %>% 
                 find_element('a') %>%
                 elem_attr('href')
  
  open_url(paste(base_url,
               link_addend,
               sep = ''))
  owner_titles <- lapply(s('#table') %>%
                           find_element('tbody') %>% 
                           find_elements('th'), 
                         elem_text)
  owners <- lapply(s('#table') %>% 
                     find_element('tbody') %>%
                     find_elements('.left-align'),
                   elem_text)
  business_string <- s('#content') %>% 
    elem_text()
  
 
  business_details_table_parse = get_business_details(business_string)
  
  #officer button appears after search
  owner_titles <- lapply(s('#table') %>% 
                           find_element('tbody') %>%
                           find_elements('th'),
                         elem_text)
  owners <- lapply(s('#table') %>% 
                     find_element('tbody') %>%
                     find_elements('.left-align'),
                   elem_text)
  print(business_details_table_parse)
  if(length(owners)==0){
    print('1.0')
    #no results on a recursive owner search
    if(depth>0 ){
      
      print('1.1')
      owner_table = data.frame(owner_name = owner_name,
                             owner_title = owner_title,
                             owner_mail_address = owner_address)
      
      results = officer_business_bind(owner_table,
                                      business_details_table_parse)

    }
    #no results on base owner search
    if(depth==0 ){
      print('1.2')
      owner_table = data.frame(owner_name = NA,
                             owner_title = NA,
                             owner_mail_address = NA)
      
      results = officer_business_bind(owner_table,
                                      business_details_table_parse)

    }
    
  }
  
  #found results
  else{
    print('officer')
    owner_name_parse <- unlist(lapply(owners, 
                               function(owner){
                                 regmatches(owner,
                            regexpr("(?<=^).*(?=\\n)",
                                    owner, 
                                    perl = TRUE))
                               }) )
    owner_title_parse <- unlist(owner_titles)
    owner_address_parse <-unlist(lapply(owners, 
                               function(owner){
                                 paste(strsplit(owner,
                                                split = '\\n')[[1]][2:3],
                                       collapse = ', ')
                                 
                               }) )
    # selenider::close_session(session)
    finance_inds <- grepl(financial_marker_string,
                          owner_name_parse)
    #if owner has financial markers, do a recursive search on it
    if(sum(finance_inds)>0){
      print('2.1')
      owners_fin = foreach(ind = which(finance_inds),
                        .combine = 'rbind') %do% {
                          fin_owner_scrape = tryCatch({
                             scrape_owner( owner_name_parse[ind],
                                         situs_pID = situs_pID , 
                                         situs_address = situs_address,
                                         veneer_owner = veneer_owner,
                                         veneer_owner_mail_address = veneer_owner_mail_address,
                                         depth = depth+1,
                                         owner_title = owner_title_parse[ind],
                                         owner_mail_address = owner_address_parse[ind],
                                         business_details_table = business_details_table_parse )
                            },error = function(cond){
                              cond
                              })
                          
                           if('error' %in% class(fin_owner_scrape)){
                             print('error')
                             owner_fin = data.frame(owner_name = owner_name_parse[ind],
                                                     owner_title = owner_title_parse[ind],
                                                     owner_address = owner_address_parse[ind])
                             
                             fin_owner_scrape = officer_business_bind(owner_fin,
                                      business_details_table_parse)
                           }
                          fin_owner_scrape
        
                        }
      
      if(sum(!finance_inds)>0){
        print('2.2')
        owners_non_fin = data.frame(owner_name = owner_name_parse,
                             owner_title = owner_title_parse,
                             owner_address = owner_address_parse)[!finance_inds,]
        
        
        owners_non_fin =officer_business_bind(owners_non_fin,
                                      business_details_table_parse)
        
        results = data.frame(rbind(owners_fin,
                                     owners_non_fin))
      }
      else{
        print('2.3')
        results = data.frame(owners_fin)
      }
    }
    else{
      print('3')
      owner_table = data.frame(owner_name = owner_name_parse,
                             owner_title = owner_title_parse,
                             owner_mail_address = owner_address_parse)
     
      results <- officer_business_bind(owner_table,
                                      business_details_table_parse)

    }
  }
  
  results$situs_pID <- situs_pID
  results$situs_address <- situs_address
  results$veneer_owner <- veneer_owner
  results$veneer_owner_mail_address <- veneer_owner_mail_address
  
  # selenider::close_session(session)
  print(results)
  return(results)
}

```

cpa_session %>%
    html_element("div#wrapper") %>%
    html_element("div#content") %>% html_element("form") %>% html_element("div") %>% html_element("div.panel panel-primary")
```{r,cache=TRUE, cache.extra=file.mtime("owner_data.csv")}

library(doRNG)
library(purrr)
doFuture::registerDoFuture()
plan(multisession)
print(Sys.time())
colnames_used <- c('owner_name',
                   'owner_title',
                   'owner_mail_address',
                   'corp_business_name',
                   'corp_TTN',
                   'corp_mail_address',
                   'corp_right_to_transact_business_tx_status',
                   'corp_state_of_formation',
                   'corp_sos_registration_status',
                   'corp_effective_sos_registration_date',
                   'corp_tx_sos_file_num',
                   'corp_registered_agent_name',
                   'situs_pID',
                   'situs_address',
                   'veneer_owner',
                   
                   'veneer_owner_mail_address')
# owner_data_netwo
owner_data <- read.csv('owner_data.csv')
empty_owner_ind <- tapply(owner_data$owner_name, owner_data$situs_pID,
                          function(x){(length(unique(x))==1)&&('' %in% x)})
empty_pIDs <-names(empty_owner_ind[which(empty_owner_ind)])
second_run_index <- which(target_properties$situs_pID %in% as.numeric(empty_pIDs))

insist_scape_owner = purrr:::insistently(scrape_owner,
                                        rate = rate_backoff(pause_base = 5,
                                                            pause_cap = 80,
                                                            pause_min = 1,
                                                            max_times = 5,
                                                            jitter = TRUE
))
owner_data <- foreach(index =second_run_index,
                      .combine = 'rbind',
                      .options.RNG = 8989,
                      .export = financial_marker_string) %dorng% {
                        owner_name =target_properties$owner_name[index]
                        owner_address = target_properties$owner_address[index]
                        situs_pID = target_properties$situs_pID[index]
                        situs_address = target_properties$situs_address[index]
                        message(index)
                        message(owner_name)
                        property_owner_info <- tryCatch({insist_scape_owner(owner_name, 
                                     situs_pID = situs_pID , 
                                     situs_address = situs_address,
                                     veneer_owner = owner_name,
                                     veneer_owner_mail_address = owner_address)},
                                 error=function(cond){
                                   cond}
                                 )
                        if((is.null(property_owner_info)) |
                           ('error' %in% class(property_owner_info))){
                          property_owner_info <- data.frame(t(c(rep(NA, 12),
                                   situs_pID,
                                   situs_address,
                                   owner_name,
                                   
                                   owner_address)))
                        }
                        
                        first_prop <- index!=1
                        colnames(property_owner_info) <- colnames_used
                        
                        data.table::fwrite(property_owner_info,

                                    'owner_data.csv',
                                    append = first_prop,
                                    sep = ','
                                    )
                        print(property_owner_info)
                        print(dim(property_owner_info))
                        return(property_owner_info)
                      }


print(Sys.time())

# write.csv(owner_data,'owner_data_total.csv')

```
